OpenSSL plugin: ignore deprecation for DES
DES_*() functions are deprecated in OpenSSL 3.0.

openssl.c:245:5: error: 'DES_string_to_key' is deprecated [-Werror,-Wdeprecated-declarations]
    DES_string_to_key ( password, &key );
    ^
/usr/local/Cellar/openssl@3/3.0.4/include/openssl/des.h:193:1: note: 'DES_string_to_key' has been explicitly marked deprecated here
OSSL_DEPRECATEDIN_3_0 void DES_string_to_key(const char *str, DES_cblock *key);
^
/usr/local/Cellar/openssl@3/3.0.4/include/openssl/macros.h:182:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
 #   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/local/Cellar/openssl@3/3.0.4/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
 #     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^