Travis-CI: fail on error
Use ./configure --enable-werror

It was not possible to use 'CFLAGS="-Werror" ./configure' because the
check in configure for cos in -lm failed instead of just reporting a warnings.
Then the link of grisbi fails with:

CCLD     grisbi
/usr/bin/ld: ./.libs/libgrisbi.a(print_transactions_list.o): undefined reference to symbol 'floor@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:903: recipe for target 'grisbi' failed

The check in configure is:
configure:13073: checking for cos in -lm
configure:13098: gcc -o conftest -Werror   conftest.c -lm   >&5
conftest.c:40:6: error: conflicting types for built-in function 'cos' [-Werror]
 char cos ();
      ^~~
cc1: all warnings being treated as errors