Fix compiler warning: implicit declaration of function ‘abs’
Add missing #include <stdlib.h>

prefs_page_reconcile_sort.c: In function ‘prefs_page_reconcile_sort_model_fill’:
prefs_page_reconcile_sort.c:174:40: error: implicit declaration of function ‘abs’ [-Werror=implicit-function-declaration]
     switch (gsb_data_payment_get_sign (abs (payment_number)))
                                        ^