Fix build for stable version with --enable-debug
GIT_HASH was defined only for odd minor version.

Version 2.0.x configured with --enable-debug failed to build with:
help.c:211:6: error: ‘GIT_HASH’ undeclared (first use in this function)
  211 |      GIT_HASH,
      |      ^~~~~~~~
help.c:211:6: note: each undeclared identifier is reported only once for each function it appears in