Add missing #include
Fix "make checkheaders"
etats_prefs_private.h:15:5: warning: implicit declaration of function ‘N_’ [-Wimplicit-function-declaration]
   15 |     N_("All"),
      |     ^~
etats_prefs_private.h:15:5: error: initializer element is not constant