Use #include "config.h" instead of <config.h>
The config.h file is local to the source code so the syntax "" must be
used.

This will help build gribsi using an Xcode project.

main.c:29:10: error: 'config.h' file not found with <angled> include; use
"quotes" instead
         ^~~~~~~~~~
	          "config.h"