Change return type of gsb_data_report_get_period_split_day()
The function now returns a GDateWeekday instead of an int so it can be
compared with another GDateWeekday.

Fix compiler warning:
etats_affiche.c: In function 'etat_affiche_affiche_total_periode':
etats_affiche.c:971:32: error: comparison of integer expressions of different signedness: 'GDateWeekday' {aka 'enum <anonymous>'} and 'int' [-Werror=sign-compare]
    ( g_date_get_weekday(date)  != (gsb_data_report_get_period_split_day (current_report_number)+ 1 )
                                ^~