Travis-CI: Mac: openssl and automake already installed
Do not install openssl and automake as it make travis to fail with:
" Your build has been stopped.
/Users/travis/.travis/job_stages: line 156: shell_session_update:
command not found "

Error: openssl 1.0.2j is already installed
To upgrade to 1.0.2l, run `brew upgrade openssl`
Error: automake 1.15 is already installed
To upgrade to 1.15.1, run `brew upgrade automake`