Do not fail for OFX include headers
In file included from ofx.c:28:
/usr/local/Cellar/libofx/0.10.0/include/libofx/libofx.h:113:42: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
  LibofxContextPtr libofx_get_new_context();
                                         ^
                                          void

We can't fix third party code. So just ignore the warning instead.
And warnings are treated as errors because of -Werror on continuous build
systems.