Add missing #include
Fix "make checkheaders"
etats_config.h:17:1: error: unknown type name ‘GtkTreeModel’
   17 | GtkTreeModel * etats_config_onglet_categ_budget_get_model       (gboolean is_categ);
      | ^~~~~~~~~~~~